apiVersion: v1
name: pilot
version: 1.2.0
appVersion: 1.2.0
tillerVersion: ">=2.7.2"
description: Helm chart for istio control plane
keywords:
  - istio
  - istiod
  - istio-discovery
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png

# inorder to compatible with previous versions so change name to pilot
# from istio-discovery
# https://github.com/istio/istio/tree/1.8.6/manifests/charts/istio-control/istio-discovery
