apiVersion: v1
appVersion: 1.8.6
description: Helm chart for all istio components
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- security
- sidecarInjectorWebhook
- pilot
- galley
name: rancher-istio
sources:
- http://github.com/istio/istio
version: 1.8.6001
helmVersion: helm_v3
kubeVersion: ">=1.16.0-0"
dependencies:
  - name: base
    version: 1.1.0
    condition: base.enabled
  - name: pilot
    version: 1.2.0
    condition: pilot.enabled
  - name: gateways
    version: 1.1.0
    condition: gateways.enabled
  - name: kiali
    version: 1.26.0
    condition: kiali.enabled
  - name: tracing
    version: 1.8.6
    condition: tracing.enabled
