apiVersion: v1
name: pilot
# This version is never actually shipped. istio/release-builder will replace it at build-time
# with the appropriate version
version: 1.0.0
appVersion: 1.0.0
tillerVersion: ">=2.7.2"
description: Helm chart for istio control plane
keywords:
  - istio
  - istiod
  - istio-discovery
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png

# inorder to compatible with previous versions so change name to pilot
# from istio-discovery
# https://github.com/istio/istio/tree/1.12.1/manifests/charts/istio-control/istio-discovery

