nameOverride: fluentd
labels: {}

image:
  repository: cnrancher/fluentd
  tag: v0.1.30-ent3
  pullPolicy: IfNotPresent

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 500Mi
  # requests:
  #   cpu: 100m
  #   memory: 200Mi
# env:

command: '["fluentd", "-c", "/fluentd/etc/config/entry/fluent.conf"]'

livenessProbe:
  enabled: true

annotations: {}

# updateStrategy:
#   type: RollingUpdate

tolerations:
  - effect: NoSchedule
    operator: Exists

nodeSelector: {}

service:
  type: ClusterIP
  ports:
    - name: metric
      port: 24231
      targetPort: metric

cluster:
  dockerRoot: /var/lib/docker
  fluentdlog: /var/lib/rancher/fluentd/log
  customlog: /var/lib/rancher/log-volumes
  rkelog: /var/lib/rancher/rke/log
  varlogpods: /var/log/pods
  varlogcontainers: /var/log/containers
  custom: /var/lib/rancher/fluentd/etc/config/custom
  libsystemddir: /usr/lib64

configmapReload:
  name: reloader
  image:
    repository: cnrancher/jimmidyson-configmap-reload
    tag: v0.7.1
    pullPolicy: IfNotPresent
  resources: {}

watcher:
  name: watcher
  image:
    repository: cnrancher/watcher
    tag: v1.0.7-ent2
    pullPolicy: IfNotPresent
  resources: {}
