partition: ""
bigip:
  url: ""
  username: ""
  password: ""
network:
  type: ""
  poolMemberType: ""
  flannelName: ""
image:
  repository: "cnrancher/k8s-bigip-ctlr"
  tag: "2.2.3"
insecure: true
certsConfigmap: ""
extraArgs:
  #key: value
